### ISSUE TITLE
EOS Issue Tracker

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/eos#6]
Some features that Eos seems to be missing (some may just need to be confirmed).

- [ ] T3D Modes (This is just a module in game, can we do something similar?)
- [ ] T3C Subsystems
- [ ] Citadels (can we just treat this as ships?)
- [ ] Citadel modules (currently none that I know of that would modify fitting stats)
- [ ] Projection (Ships and fits)
- [ ] Fighters probably don't work

Potential Bugs/Issues with Eos:
- Need to confirm, but seems Eos only returns an except for each error if the error is the same type.  Ideally it returns an exception with all issues with the fit.

**Comment by Regner** [comment]
When you get a chance can we get this list broken out into separate issues?

**Comment by Ebag333** [comment]
Done.
